# Generated by Django 4.0.6 on 2022-07-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='email_address',
        ),
    ]
