# Generated by Django 4.0.6 on 2022-07-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_school_email_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
    ]
