# Generated by Django 4.0.6 on 2022-07-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_school_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(blank=True, default='Primary', max_length=20, verbose_name='School Category'),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='username',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='School Name'),
        ),
    ]
