# Generated by Django 4.0.6 on 2022-07-30 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_address_remove_profile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(blank=True, max_length=20, verbose_name='School Category'),
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
