# Generated by Django 4.0.6 on 2022-07-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_school_category_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='school',
        ),
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.ForeignKey(default='Nur&Pri', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.cat'),
        ),
    ]
