# Generated by Django 4.0.6 on 2022-07-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cat_school_cat_name_alter_school_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='category',
            new_name='school_category',
        ),
    ]
