# Generated by Django 4.0.6 on 2022-07-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_school_school_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cat'),
        ),
    ]
