# Generated by Django 4.0.6 on 2022-07-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_school_school_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='picture',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
