# Generated by Django 4.0.6 on 2022-08-01 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='img')),
                ('first_name', models.CharField(default='damnoit', max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(default='damnoit', max_length=30, verbose_name='Last Name')),
                ('middle_name', models.CharField(max_length=30, null=True, verbose_name='Middle Name')),
                ('NIN', models.BigIntegerField(null=True)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], default='damnoit', max_length=10)),
                ('class_name', models.CharField(choices=[('Nursery 1', 'Nur 1'), ('Nursery 2', 'Nur 2'), ('Primary 1', 'Pri 1'), ('Primary 2', 'Pri 2'), ('Primary 3', 'Pri 3'), ('Primary 4', 'Pri 4'), ('Primary 5', 'Pri 5'), ('Primary 6', 'Pri 6')], default='damnoit', max_length=20)),
                ('sponsor_name', models.CharField(default='Parents', max_length=100, verbose_name='Name of Sponsor')),
                ('sponsor_phone', models.CharField(default='damnoit', max_length=11, verbose_name="Sponsor's Phone Number")),
                ('nationality', models.CharField(default='Nigerian', max_length=20)),
                ('session', models.CharField(max_length=9, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(null=True, upload_to='img')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_debtors.student')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('credit_status', models.CharField(choices=[('Paid', 'paid'), ('owing', 'owing')], max_length=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt', to='my_debtors.student')),
            ],
        ),
    ]
